### ISSUE TITLE
app не синкает

### ISSUE THREAD

**Issue by cobr123** [NikitaMelnikov/scala-russia-2019-bazel#1]
```
Syncing project: Sync (incremental)...
Updating VCS...
Running Bazel info...
Command: bazel info --tool_tag=ijwb:IDEA:community --curses=no --color=yes --progress_in_terminal_title=no --

Command: git diff --name-status --no-renames 253d77f469b3fb62a8ef08146c83b7031c4d7aea

INFO: Writing tracer profile to '/home/rtabulov/.cache/bazel/_bazel_rtabulov/ef29bd25d23c4fd653164b4165355d4f/command.profile.gz'
Computing VCS working set...
Your working set is empty
Querying targets in project directories...
Command: bazel query --tool_tag=ijwb:IDEA:community --output=label_kind --keep_going "attr(\"tags\", \"^((?!manual).)*$\", //...:all - //bazel-bin/...:all - //bazel-genfiles/...:all - //bazel-out/...:all - //bazel-testlogs/...:all - //bazel-scala-russia-2019-bazel/...:all - //.ijwb/...:all)" --

60 targets found under project directories; syncing 58 of them.
Sync targets from project view directories:
  //3rdparty/jvm/org/slf4j:log4j_over_slf4j
  //3rdparty/jvm/org/slf4j:jul_to_slf4j
  //3rdparty/jvm/org/slf4j:jcl_over_slf4j
  //3rdparty/jvm/org/scala_lang/modules:scala_parser_combinators
  //3rdparty/jvm/org/scala_lang:scala_compiler
  //3rdparty/jvm/io/grpc:grpc_services
  //3rdparty/jvm/com/google/re2j:re2j
  //3rdparty/jvm/com/google/protobuf:protobuf_java_util
  //dependencies:test
  //3rdparty/jvm/org/scala_lang/modules:scala_xml
  //:app
  //dependencies:logging
  //3rdparty/jvm/org/scala_lang:scala_reflect
  //3rdparty/jvm/ch/qos/logback:logback_classic
  //3rdparty/jvm/org/slf4j:slf4j_api
  //3rdparty/jvm/ch/qos/logback:logback_core
  //dependencies:grpc
  //3rdparty/jvm/io/grpc:grpc_testing
  //3rdparty/jvm/org/mockito:mockito_core
  //3rdparty/jvm/org/objenesis:objenesis
  //3rdparty/jvm/net/bytebuddy:byte_buddy_agent
  //3rdparty/jvm/net/bytebuddy:byte_buddy
  //3rdparty/jvm/junit:junit
  //3rdparty/jvm/org/hamcrest:hamcrest_core
  //3rdparty/jvm/io/grpc:grpc_netty_shaded
  //3rdparty/jvm/io/grpc:grpc_stub
  //3rdparty/jvm/io/grpc:grpc_protobuf
  //3rdparty/jvm/io/grpc:grpc_protobuf_lite
  //3rdparty/jvm/com/google/protobuf:protobuf_lite
  //3rdparty/jvm/io/grpc:grpc_core
  //3rdparty/jvm/org/codehaus/mojo:animal_sniffer_annotations
  //3rdparty/jvm/io/opencensus:opencensus_contrib_grpc_metrics
  //3rdparty/jvm/io/opencensus:opencensus_api
  //3rdparty/jvm/io/grpc:grpc_context
  //3rdparty/jvm/com/google/errorprone:error_prone_annotations
  //3rdparty/jvm/com/google/code/gson:gson
  //3rdparty/jvm/com/google/code/findbugs:jsr305
  //3rdparty/jvm/com/google/guava:guava
  //3rdparty/jvm/org/checkerframework:checker_compat_qual
  //3rdparty/jvm/com/google/j2objc:j2objc_annotations
  //3rdparty/jvm/com/google/api/grpc:proto_google_common_protos
  //3rdparty/jvm/com/thesamet/scalapb:lenses_2_12
  //3rdparty/jvm/com/lihaoyi:fastparse_2_12
  //3rdparty/jvm/com/lihaoyi:fastparse_utils_2_12
  //3rdparty/jvm/com/lihaoyi:sourcecode_2_12
  //3rdparty/jvm/org/scala_lang:scala_library
  //3rdparty/jvm/com/google/protobuf:protobuf_java
  //dependencies:config
  //3rdparty/jvm/com/typesafe:config
  //:demo_proto

Plus 8 more targets
Building Bazel targets...
Command: bazel build --tool_tag=ijwb:IDEA:community --keep_going --build_event_binary_file=/tmp/intellij-bep-1eae94ba-e7a1-43a9-883e-1615cc93c49d --nobuild_event_binary_file_path_conversion --curses=no --color=yes --progress_in_terminal_title=no --aspects=@intellij_aspect//:intellij_info_bundled.bzl%intellij_info_aspect --override_repository=intellij_aspect=/home/rtabulov/.IdeaIC2019.2/config/plugins/ijwb/aspect --output_groups=intellij-info-generic,intellij-info-java,intellij-resolve-java -- //3rdparty/jvm/org/slf4j:log4j_over_slf4j //3rdparty/jvm/org/slf4j:jul_to_slf4j //3rdparty/jvm/org/slf4j:jcl_over_slf4j //3rdparty/jvm/org/scala_lang/modules:scala_parser_combinators //3rdparty/jvm/org/scala_lang:scala_compiler //3rdparty/jvm/io/grpc:grpc_services //3rdparty/jvm/com/google/re2j:re2j //3rdparty/jvm/com/google/protobuf:protobuf_java_util //dependencies:test //3rdparty/jvm/org/scala_lang/modules:scala_xml //:app //dependencies:logging //3rdparty/jvm/org/scala_lang:scala_reflect //...
INFO: Writing tracer profile to '/home/rtabulov/.cache/bazel/_bazel_rtabulov/ef29bd25d23c4fd653164b4165355d4f/command.profile.gz'
Loading: 
Loading: 0 packages loaded
Analyzing: 58 targets (29 packages loaded, 0 targets configured)
Analyzing: 58 targets (118 packages loaded, 938 targets configured)
INFO: Analyzed 58 targets (177 packages loaded, 1223 targets configured).

INFO: Found 58 targets...
[3 / 16] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[436 / 439] scala //:app; 1s worker
ERROR: /home/rtabulov/IdeaProjects/scala-russia-2019-bazel/BUILD:4:1: Couldn't build file app.jar: scala //:app failed (Exit 1)
error: Error while emitting DemoAppStarter.scala
assertion failed:
  Bad superClass for class GreetingsServiceGrpc$GreetingsService: <none>
     while compiling: app/src/main/scala/demo/DemoAppStarter.scala
        during phase: jvm
     library version: version 2.12.8
    compiler version: version 2.12.8
  reconstructed args: -encoding utf8 -classpath bazel-out/k8-fastbuild/bin/demo_proto_scalapb.jar:external/scala_proto_rules_scalapb_runtime/scalapb-runtime_2.12-0.8.4.jar:bazel-out/host/bin/external/com_google_protobuf/libprotobuf_java.jar:external/scala_proto_rules_scalapb_lenses/lenses_2.12-0.8.4.jar:external/scala_proto_rules_scalapb_fastparse/fastparse_2.12-1.0.0.jar:external/io_bazel_rules_scala_scala_library/scala-library-2.12.8.jar:external/scala_proto_rules_scalapb_runtime_grpc/scalapb-runtime-grpc_2.12-0.8.4.jar:external/scala_proto_rules_grpc_core/grpc-core-1.19.0.jar:external/scala_proto_rules_grpc_stub/grpc-stub-1.19.0.jar:external/scala_proto_rules_grpc_protobuf/grpc-protobuf-1.19.0.jar:external/scala_proto_rules_grpc_netty/grpc-netty-1.19.0.jar:external/scala_proto_rules_grpc_context/grpc-context-1.19.0.jar:external/scala_proto_rules_guava/guava-26.0-android.jar:external/scala_proto_rules_opencensus_api/opencensus-api-0.22.1.jar:external/scala_proto_rules_opencensus_impl/opencensus-impl-0.22.1.jar:external/scala_proto_rules_disruptor/disruptor-3.4.2.jar:external/scala_proto_rules_opencensus_impl_core/opencensus-impl-core-0.22.1.jar:external/scala_proto_rules_opencensus_contrib_grpc_metrics/opencensus-contrib-grpc-metrics-0.22.1.jar:external/scala_proto_rules_google_instrumentation/instrumentation-api-0.3.0.jar:external/scala_proto_rules_netty_codec/netty-codec-4.1.32.Final.jar:external/scala_proto_rules_netty_codec_http/netty-codec-http-4.1.32.Final.jar:external/scala_proto_rules_netty_codec_http2/netty-codec-http2-4.1.32.Final.jar:external/scala_proto_rules_netty_codec_socks/netty-codec-socks-4.1.32.Final.jar:external/scala_proto_rules_netty_handler/netty-handler-4.1.32.Final.jar:external/scala_proto_rules_netty_buffer/netty-buffer-4.1.32.Final.jar:external/scala_proto_rules_netty_transport/netty-transport-4.1.32.Final.jar:external/scala_proto_rules_netty_resolver/netty-resolver-4.1.32.Final.jar:external/scala_proto_rules_netty_common/netty-common-4.1.32.Final.jar:external/scala_proto_rules_netty_handler_proxy/netty-handler-proxy-4.1.32.Final.jar:bazel-out/k8-fastbuild/bin/dependencies/config.jar:external/com_typesafe_config/jar/com_typesafe_config.jar:bazel-out/k8-fastbuild/bin/dependencies/logging.jar:external/org_slf4j_slf4j_api/jar/org_slf4j_slf4j_api.jar:external/ch_qos_logback_logback_classic/jar/ch_qos_logback_logback_classic.jar:external/ch_qos_logback_logback_core/jar/ch_qos_logback_logback_core.jar:external/com_typesafe_scala_logging_scala_logging_2_12/jar/com_typesafe_scala_logging_scala_logging_2_12.jar:bazel-out/k8-fastbuild/bin/3rdparty/jvm/org/scala_lang/scala_library.jar:bazel-out/k8-fastbuild/bin/3rdparty/jvm/org/scala_lang/scala_reflect.jar:external/io_bazel_rules_scala_scala_reflect/scala-reflect-2.12.8.jar:bazel-out/k8-fastbuild/bin/dependencies/grpc.jar:external/com_google_code_findbugs_jsr305/jar/com_google_code_findbugs_jsr305.jar:external/com_google_code_gson_gson/jar/com_google_code_gson_gson.jar:external/com_google_errorprone_error_prone_annotations/jar/com_google_errorprone_error_prone_annotations.jar:external/com_google_j2objc_j2objc_annotations/jar/com_google_j2objc_j2objc_annotations.jar:external/org_checkerframework_checker_compat_qual/jar/org_checkerframework_checker_compat_qual.jar:external/com_google_guava_guava/jar/com_google_guava_guava.jar:external/io_opencensus_opencensus_api/jar/io_opencensus_opencensus_api.jar:external/io_opencensus_opencensus_contrib_grpc_metrics/jar/io_opencensus_opencensus_contrib_grpc_metrics.jar:external/org_codehaus_mojo_animal_sniffer_annotations/jar/org_codehaus_mojo_animal_sniffer_annotations.jar:external/io_grpc_grpc_core/jar/io_grpc_grpc_core.jar:external/io_grpc_grpc_context/jar/io_grpc_grpc_context.jar:external/com_google_api_grpc_proto_google_common_protos/jar/com_google_api_grpc_proto_google_common_protos.jar:external/com_google_protobuf_protobuf_java/jar/com_google_protobuf_protobuf_java.jar:external/io_grpc_grpc_protobuf/jar/io_grpc_grpc_protobuf.jar:external/com_google_protobuf_protobuf_lite/jar/com_google_protobuf_protobuf_lite.jar:external/io_grpc_grpc_protobuf_lite/jar/io_grpc_grpc_protobuf_lite.jar:external/io_grpc_grpc_stub/jar/io_grpc_grpc_stub.jar:external/org_hamcrest_hamcrest_core/jar/org_hamcrest_hamcrest_core.jar:external/junit_junit/jar/junit_junit.jar:external/net_bytebuddy_byte_buddy/jar/net_bytebuddy_byte_buddy.jar:external/net_bytebuddy_byte_buddy_agent/jar/net_bytebuddy_byte_buddy_agent.jar:external/org_objenesis_objenesis/jar/org_objenesis_objenesis.jar:external/org_mockito_mockito_core/jar/org_mockito_mockito_core.jar:external/io_grpc_grpc_testing/jar/io_grpc_grpc_testing.jar:external/io_grpc_grpc_netty_shaded/jar/io_grpc_grpc_netty_shaded.jar:external/com_thesamet_scalapb_scalapb_runtime_2_12/jar/com_thesamet_scalapb_scalapb_runtime_2_12.jar:external/com_lihaoyi_fastparse_2_12/jar/com_lihaoyi_fastparse_2_12.jar:external/com_lihaoyi_fastparse_utils_2_12/jar/com_lihaoyi_fastparse_utils_2_12.jar:external/com_lihaoyi_sourcecode_2_12/jar/com_lihaoyi_sourcecode_2_12.jar:external/com_thesamet_scalapb_lenses_2_12/jar/com_thesamet_scalapb_lenses_2_12.jar:external/com_thesamet_scalapb_scalapb_runtime_grpc_2_12/jar/com_thesamet_scalapb_scalapb_runtime_grpc_2_12.jar -deprecation -language:dynamics -language:postfixOps -language:reflectiveCalls -language:implicitConversions -language:higherKinds -language:existentials -language:experimental.macros -feature -Ypartial-unification -d bazel-out/k8-fastbuild/bin/tmp14265064333218164280 -unchecked

  last tree to typer: TypeTree(class Boolean)
       tree position: line 7 of app/src/main/scala/demo/DemoAppStarter.scala
            tree tpe: Boolean
              symbol: (final abstract) class Boolean in package scala
   symbol definition: final abstract class Boolean extends  (a ClassSymbol)
      symbol package: scala
       symbol owners: class Boolean
           call site: constructor DemoService in class DemoService in package demo

== Source file context for tree position ==

     4 import demo.DemoService.GreetingsServiceGrpc
     5 import io.grpc.netty.shaded.io.grpc.netty.NettyServerBuilder
     6
     7 object DemoAppStarter extends App with LazyLogging {
     8   val app = new DemoApp()
     9   logger.info(s"Application version: ${app.getVersion()}")
    10
error: Error while emitting DemoService.scala
assertion failed: ClassBType.info not yet assigned: Ldemo/DemoService;
two errors found
two errors found
java.lang.RuntimeException: Build failed
	at io.bazel.rulesscala.scalac.ScalacProcessor.compileScalaSources(ScalacProcessor.java:244)
	at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:69)
	at io.bazel.rulesscala.worker.GenericWorker.runPersistentWorker(GenericWorker.java:45)
	at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:111)
	at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
INFO: Elapsed time: 5.066s, Critical Path: 1.76s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
INFO: Build Event Protocol files produced successfully.
FAILED: Build did NOT complete successfully
build invocation result: build_error
Sync was successful, but there were Bazel build errors. The project may not be fully updated or resolve until fixed. If the errors are from your working set, please uncheck 'Bazel > Sync > Expand Sync to Working Set' and try again.
Parsing build outputs...
Total rules: 106, new/changed: 0, removed: 0
Reading IDE info result...
Updating target map
Loaded 0 aspect files, total size 0kB
Target map size: 101
Reading jdeps files...
Loaded 0 jdeps files, total size 0kB
Reading package manifests...
Java content entry count: 1
Updating Jar Cache...
Prefetching files...
Refreshing files
Computing directory structure...
Committing project structure...
Workspace has 79 libraries
Workspace has 2 modules
Updating in-memory state...
Sync finished

Timing summary:
BlazeInvocation: 7.3s, Prefetching: 0ms, Other: 354ms

```

**Comment by shapeless-space** [comment]
Привет, спасибо за репорт

А какая версия bazel используется?

**Comment by cobr123** [comment]
Build label: 1.0.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Oct 10 10:16:08 2019 (1570702568)
Build timestamp: 1570702568
Build timestamp as int: 1570702568

**Comment by shapeless-space** [comment]
Смог воспроизвести у себя, пофиксил в #2

**Comment by cobr123** [comment]
Благодарю!
